In [3]:
import torch
print(torch.__version__)

2.6.0


In [4]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


## Creating a Tensor

In [5]:
# using empty
a = torch.empty(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
# check type
type(a)

torch.Tensor

In [7]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# using rand
torch.rand(2,3)

tensor([[0.2424, 0.8584, 0.5845],
        [0.8203, 0.9371, 0.2707]])

In [10]:
# use of seed
torch.rand(2,3)

tensor([[0.4910, 0.4796, 0.9035],
        [0.6375, 0.9990, 0.3204]])

In [11]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [15]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
x.shape

torch.Size([2, 3])

In [17]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [22]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [23]:
# find data type
x.dtype

torch.int64

In [25]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [26]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [27]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [68]:
x = torch.rand(2,2)
x

tensor([[0.6574, 0.3451],
        [0.0453, 0.9798]])

In [69]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.4321, 0.1191],
        [0.0021, 0.9599]])

### 2. Element wise operation

In [70]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.5548, 0.6868, 0.4920],
        [0.0748, 0.9605, 0.3271]])
tensor([[0.0103, 0.9516, 0.2855],
        [0.2324, 0.9141, 0.7668]])


In [71]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.0010, 0.6868, 0.2065],
        [0.0748, 0.0464, 0.3271]])

In [81]:
c = torch.tensor([1, -2, 3, -4])

In [82]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [83]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [84]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [85]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [86]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [87]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [88]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [89]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[1., 2., 4.],
        [7., 2., 5.]])

In [90]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([ 7., 14.])

In [91]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([4.0000, 2.0000, 4.5000])

In [92]:
# median
torch.median(e)

tensor(2.)

In [93]:
# max and min
torch.max(e)
torch.min(e)

tensor(1.)

In [94]:
# product
torch.prod(e)

tensor(560.)

In [95]:
# standard deviation
torch.std(e)

tensor(2.2583)

In [96]:
# variance
torch.var(e)

tensor(5.1000)

In [97]:
# argmax
torch.argmax(e)

tensor(3)

In [98]:
# argmin
torch.argmin(e)

tensor(0)

### 4. Matrix operations

In [106]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[1, 0, 5],
        [1, 0, 0]])
tensor([[2, 2],
        [3, 7],
        [1, 5]])


In [108]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[ 7, 27],
        [ 2,  2]])

In [109]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [110]:
# transpose
torch.transpose(f, 0, 1)

tensor([[1, 1],
        [0, 0],
        [5, 0]])

In [111]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[0., 2., 3.],
        [7., 0., 2.],
        [5., 2., 8.]])

In [113]:
# determinant
torch.det(h)

tensor(-50.0000)

In [114]:
# inverse
torch.inverse(h)

tensor([[ 0.0800,  0.2000, -0.0800],
        [ 0.9200,  0.3000, -0.4200],
        [-0.2800, -0.2000,  0.2800]])

### 5. Comparison operations

In [115]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[0, 2, 5],
        [3, 6, 7]])
tensor([[8, 1, 2],
        [3, 2, 7]])


In [116]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[ True,  True,  True],
        [False,  True, False]])

### 6. Special functions

In [117]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[9., 3., 9.],
        [7., 7., 5.]])

In [118]:
# log
torch.log(k)

tensor([[2.1972, 1.0986, 2.1972],
        [1.9459, 1.9459, 1.6094]])

In [119]:
# exp
torch.exp(k)

tensor([[8103.0840,   20.0855, 8103.0840],
        [1096.6332, 1096.6332,  148.4132]])

In [120]:
# sqrt
torch.sqrt(k)

tensor([[3.0000, 1.7321, 3.0000],
        [2.6458, 2.6458, 2.2361]])

In [121]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9999, 0.9526, 0.9999],
        [0.9991, 0.9991, 0.9933]])

In [122]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.8808, 0.0180, 0.9820],
        [0.1192, 0.9820, 0.0180]])

In [123]:
# relu
torch.relu(k)

tensor([[9., 3., 9.],
        [7., 7., 5.]])

## Inplace Operations

In [124]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9991, 0.1133, 0.0135],
        [0.1450, 0.7819, 0.3134]])
tensor([[0.2983, 0.3436, 0.2028],
        [0.9792, 0.4947, 0.3617]])


In [125]:
m.add_(n)

tensor([[1.2974, 0.4569, 0.2163],
        [1.1242, 1.2766, 0.6751]])

In [126]:
m

tensor([[1.2974, 0.4569, 0.2163],
        [1.1242, 1.2766, 0.6751]])

In [127]:
n

tensor([[0.2983, 0.3436, 0.2028],
        [0.9792, 0.4947, 0.3617]])

In [128]:
torch.relu(m)

tensor([[1.2974, 0.4569, 0.2163],
        [1.1242, 1.2766, 0.6751]])

In [129]:
m.relu_()

tensor([[1.2974, 0.4569, 0.2163],
        [1.1242, 1.2766, 0.6751]])

In [130]:
m

tensor([[1.2974, 0.4569, 0.2163],
        [1.1242, 1.2766, 0.6751]])

## Copying a Tensor

In [131]:
a = torch.rand(2,3)
a

tensor([[0.9687, 0.0359, 0.3041],
        [0.9867, 0.1290, 0.6887]])

In [132]:
b = a

In [133]:
b

tensor([[0.9687, 0.0359, 0.3041],
        [0.9867, 0.1290, 0.6887]])

In [134]:
a[0][0] = 0

In [135]:
a

tensor([[0.0000, 0.0359, 0.3041],
        [0.9867, 0.1290, 0.6887]])

In [136]:
b

tensor([[0.0000, 0.0359, 0.3041],
        [0.9867, 0.1290, 0.6887]])

In [137]:
id(a)

4754819008

In [138]:
id(b)

4754819008

In [139]:
b = a.clone()

In [140]:
a

tensor([[0.0000, 0.0359, 0.3041],
        [0.9867, 0.1290, 0.6887]])

In [141]:
b

tensor([[0.0000, 0.0359, 0.3041],
        [0.9867, 0.1290, 0.6887]])

In [142]:
a[0][0] = 10

In [143]:
a

tensor([[10.0000,  0.0359,  0.3041],
        [ 0.9867,  0.1290,  0.6887]])

In [144]:
b

tensor([[0.0000, 0.0359, 0.3041],
        [0.9867, 0.1290, 0.6887]])

In [145]:
id(a)

4754819008

In [146]:
id(b)

4754818368